---
- name: Set up modded Minecraft server
  hosts: localhost:all
  become: yes
  vars:
    # modpack server zip
    modpack_server_zip_url: "https://mediafilez.forgecdn.net/files/5410/874/server-1.0.3.zip"

    # the name of the modpack server zip file
    modpack_server_zip_file: "atm-9-to-the-sky-server-1.0.3.zip"

    # the name of the nested server folder in the zip
    nested_server_folder_name: "server-1.0.3"

    # the version of the modpack
    modpack_version: "1.0.3"

    # java mem flags
    java_mem_flags: "-Xms4G -Xmx8G"

    # java bin path
    java_bin_path: "/usr/lib/jvm/java-17-openjdk-amd64/bin/java"

    # forge installer filename
    forge_installer_filename: "forge-1.20.1-47.2.20-installer.jar"

    # the folder name for the Minecraft server
    minecraft_folder_name: "atm-9-to-the-sky"

    # the name of the systemd service
    minecraft_service_name: "minecraft-atm-9-to-the-sky"

    
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Ensure Java 17 is installed
      apt:
        name: openjdk-17-jre
        state: present

    - name: Ensure Java 17 is the default Java
      alternatives:
        name: java
        path: "{{ java_bin_path }}"


    - name: Create minecraft user
      user:
        name: minecraft
        state: present

    - name: Create a directory for the Minecraft server
      file:
        path: "/opt/minecraft/{{ minecraft_folder_name }}"
        state: directory
        owner: minecraft
        group: minecraft
        mode: '0755'

    - name: Download modpack
      get_url:
        url: "{{ modpack_server_zip_url }}"
        dest: "/opt/minecraft/{{ minecraft_folder_name }}/{{ modpack_server_zip_file }}"
        mode: '0755'

    - name: Extract modpack with unzip
      shell: |
        cd "/opt/minecraft/{{ minecraft_folder_name }}"
        if [ ! -f ./already_extracted ]; then
          echo "Extracting server modpack..."
          unzip "{{ modpack_server_zip_file }}"
          touch ./already_extracted
        else
          echo "Server already extracted. Skipping."
        fi

    - name: "Flatten folder structure"
      shell: |
        FOLDER=/opt/minecraft/{{ minecraft_folder_name }}/{{nested_server_folder_name}}

        if [ -d $FOLDER ]; then
          echo "Flattening folder structure of $FOLDER as it exists..."
          mv $FOLDER/* ./

          echo "Deleting folder $FOLDER as it's no longer needed..."
          rm -r $FOLDER
        else
          echo "Folder structure $FOLDER is already flattened or does not exist. Skipping."
        fi
      args: 
        chdir: "/opt/minecraft/{{ minecraft_folder_name }}"

    - name: Accept EULA
      copy:
        dest: "/opt/minecraft/{{minecraft_folder_name}}/eula.txt"
        content: "eula=true"

    - name: Run server install script
      shell: |
        if [ ! -f ./already_installed ]; then 
          {{java_bin_path}} -jar {{forge_installer_filename}} --installServer
          touch ./already_installed
        else
          echo "Server already installed. Skipping."
        fi
      args:
        chdir: "/opt/minecraft/{{minecraft_folder_name}}"

    - name: Create a systemd service for Minecraft
      copy:
        dest: /etc/systemd/system/{{minecraft_service_name}}.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft/{{minecraft_folder_name}}
          ExecStart=/bin/bash /opt/minecraft/{{minecraft_folder_name}}/startserver.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Set user JVM args
      copy:
        dest: "/opt/minecraft/{{minecraft_folder_name}}/user_jvm_args.txt"
        content: |
          {{java_mem_flags}}

    - name: Set permissions for the entire minecraft folder
      file:
        path: "/opt/minecraft/"
        state: directory
        recurse: yes
        owner: minecraft
        group: minecraft

    - name: Start and enable the Minecraft service
      systemd:
        name: "{{minecraft_service_name}}"
        state: started
        enabled: yes

    - name: Wait for the Minecraft server to start
      wait_for:
        port: 25565
        delay: 10
        timeout: 300

    - name: Restart the Minecraft server
      systemd:
        name: "{{minecraft_service_name}}"
        state: restarted

    - name: Check the status and logs of the Minecraft server
      shell: |
        systemctl status {{minecraft_service_name}}
        journalctl -u {{minecraft_service_name}}
      register: minecraft_status

    - name: Connect to TCP port 25565 to verify the Minecraft server is running
      wait_for:
        host: "{{ ansible_host }}"
        port: 25565
        timeout: 300